export const START_LOADING_FLIGHTS = 'START_LOADING_FLIGHTS';
export const LOADING_FLIGHTS_SUCCESS = 'LOADING_FLIGHTS_SUCCESS';
export const SET_ARRIVAL = 'SET_ARRIVAL';
export const SET_DEPARTURE = 'SET_DEPARTURE';
export const LOADING_FLIGHTS_ERROR = 'LOADING_FLIGHTS_ERROR';

export const UPDATE_DATE = 'UPDATE_DATE';

export const SEARCH_QUERY = 'SEARCH_QUERY';
